<a href="https://colab.research.google.com/github/SamShinwari/Advanced-AI-Bootcamp-2026/blob/main/Single_Layer_Perceptron_Using_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

AND  gate dataset

In [13]:
# Input features
X = np.array([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
])

# Target labels
y = np.array([
    [0.],
    [0.],
    [0.],
    [1.]
])

##build perceptron model

In [14]:
model = Sequential([
    Dense(
        units=1,
        activation='sigmoid',
        input_shape=(2,)
    )
])

###compile the model

In [15]:
model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

###train the model

In [16]:
history = model.fit(
    X,
    y,
    epochs=1000,
    verbose=0
)

###model evaulation

In [17]:
loss, accuracy = model.evaluate(X, y, verbose=0)

print("Loss:", loss)
print("Accuracy:", accuracy)

Loss: 0.471792608499527
Accuracy: 0.75


###model prediction

In [18]:
predictions = model.predict(X)

print("Probabilities:")
print(predictions)

print("\nBinary Predictions:")
print((predictions >= 0.5).astype(int))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Probabilities:
[[0.21900056]
 [0.42809835]
 [0.22623159]
 [0.43835837]]

Binary Predictions:
[[0]
 [0]
 [0]
 [0]]


### view learned weight

In [19]:
weights, bias = model.layers[0].get_weights()

print("Weights:")
print(weights)

print("\nBias:")
print(bias)

Weights:
[[0.04178676]
 [0.9818861 ]]

Bias:
[-1.2715001]
