<a href="https://colab.research.google.com/github/SamShinwari/Advanced-AI-Bootcamp-2026/blob/main/SingleLayerPerceptron_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Single Layer Perceptron in Pytorch

###In this code i used the Pytorch library for Single Layer Perceptron
####I used the AND gate input data

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# Input features
X = torch.tensor([
    [0., 0.],
    [0., 1.],
    [1., 0.],
    [1., 1.]
])

# Target labels
y = torch.tensor([
    [0.],
    [0.],
    [0.],
    [1.]
])

In [3]:
class Perceptron(nn.Module):
    def __init__(self):
        super(Perceptron, self).__init__()

        self.linear = nn.Linear(2, 1)
        self.activation = nn.Sigmoid()

    def forward(self, x):
        x = self.linear(x)
        x = self.activation(x)
        return x

In [4]:
model = Perceptron()

In [5]:
criterion = nn.BCELoss()           # Binary Cross Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [6]:
epochs = 1000

for epoch in range(epochs):

    # Forward pass
    outputs = model(X)

    # Compute loss
    loss = criterion(outputs, y)

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}")

Epoch [100/1000], Loss: 0.4360
Epoch [200/1000], Loss: 0.3475
Epoch [300/1000], Loss: 0.2913
Epoch [400/1000], Loss: 0.2519
Epoch [500/1000], Loss: 0.2224
Epoch [600/1000], Loss: 0.1993
Epoch [700/1000], Loss: 0.1807
Epoch [800/1000], Loss: 0.1653
Epoch [900/1000], Loss: 0.1522
Epoch [1000/1000], Loss: 0.1411


In [7]:
with torch.no_grad():

    outputs = model(X)

    predictions = (outputs >= 0.5).float()

    print("\nPredictions:")
    print(predictions)

    print("\nActual:")
    print(y)


Predictions:
tensor([[0.],
        [0.],
        [0.],
        [1.]])

Actual:
tensor([[0.],
        [0.],
        [0.],
        [1.]])


## i view learned parameter

In [8]:
print("\nWeights:")
print(model.linear.weight)

print("\nBias:")
print(model.linear.bias)


Weights:
Parameter containing:
tensor([[3.0723, 3.0765]], requires_grad=True)

Bias:
Parameter containing:
tensor([-4.8277], requires_grad=True)
